---
- name: Check if docker is installed
  ansible.builtin.command: docker --version
  register: get_docker_version_out

- name: Debug
  debug:
    var: get_docker_version_out

- name: Set user
  ansible.builtin.set_fact:
    current_user: "{{ ansible_user_id }}"

- name: Install Docker
  become: true
  when: get_docker_version_out.rc != 0
  block:
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: present

    - name: Add Docker repo to apt
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin

    - name: Ensure docker service started and enabled
      ansible.builtin.service:
        name: docker
        enabled: true
        state: restarted

    - name: Add docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ current_user }}"
        groups: docker
        append: true
