---
- hosts: minikube
  tags:
    - install
  roles:
    - install

- hosts: minikube
  tags:
    - noinstall
    - start
  roles:
    - start

- hosts: minikube
  tags:
    - noinstall
    - configure
  roles:
    - configure
